var nameList = [
  "Time",
  "Past",
  "Future",
  "Dev",
  "Fly",
  "Flying",
  "Soar",
  "Soaring",
  "Power",
  "Falling",
  "Fall",
  "Jump",
  "Cliff",
  "Mountain",
  "Rend",
  "Red",
  "Blue",
  "Green",
  "Yellow",
  "Gold",
  "Demon",
  "Demonic",
  "Panda",
  "Cat",
  "Kitty",
  "Kitten",
  "Zero",
  "Memory",
  "Trooper",
  "XX",
  "Bandit",
  "Fear",
  "Light",
  "Glow",
  "Tread",
  "Deep",
  "Deeper",
  "Deepest",
  "Mine",
  "Your",
  "Worst",
  "Enemy",
  "Hostile",
  "Force",
  "Video",
  "Game",
  "Donkey",
  "Mule",
  "Colt",
  "Cult",
  "Cultist",
  "Magnum",
  "Gun",
  "Assault",
  "Recon",
  "Trap",
  "Trapper",
  "Redeem",
  "Code",
  "Script",
  "Writer",
  "Near",
  "Close",
  "Open",
  "Cube",
  "Circle",
  "Geo",
  "Genome",
  "Germ",
  "Spaz",
  "Shot",
  "Echo",
  "Beta",
  "Alpha",
  "Gamma",
  "Omega",
  "Seal",
  "Squid",
  "Money",
  "Cash",
  "Lord",
  "King",
  "Duke",
  "Rest",
  "Fire",
  "Flame",
  "Morrow",
  "Break",
  "Breaker",
  "Numb",
  "Ice",
  "Cold",
  "Rotten",
  "Sick",
  "Sickly",
  "Janitor",
  "Camel",
  "Rooster",
  "Sand",
  "Desert",
  "Dessert",
  "Hurdle",
  "Racer",
  "Eraser",
  "Erase",
  "Big",
  "Small",
  "Short",
  "Tall",
  "Sith",
  "Bounty",
  "Hunter",
  "Cracked",
  "Broken",
  "Sad",
  "Happy",
  "Joy",
  "Joyful",
  "Crimson",
  "Destiny",
  "Deceit",
  "Lies",
  "Lie",
  "Honest",
  "Destined",
  "Bloxxer",
  "Hawk",
  "Eagle",
  "Hawker",
  "Walker",
  "Zombie",
  "Sarge",
  "Capt",
  "Captain",
  "Punch",
  "One",
  "Two",
  "Uno",
  "Slice",
  "Slash",
  "Melt",
  "Melted",
  "Melting",
  "Fell",
  "Wolf",
  "Hound",
  "Legacy",
  "Sharp",
  "Dead",
  "Mew",
  "Chuckle",
  "Bubba",
  "Bubble",
  "Sandwich",
  "Smasher",
  "Extreme",
  "Multi",
  "Universe",
  "Ultimate",
  "Death",
  "Ready",
  "Monkey",
  "Elevator",
  "Wrench",
  "Grease",
  "Head",
  "Theme",
  "Grand",
  "Cool",
  "Kid",
  "Boy",
  "Girl",
  "Vortex",
  "Paradox",
];

export function generateRandomName() {
  return nameList[Math.floor(Math.random() * nameList.length)];
}

export function getRandomMessage() {
  const messages = [
    "Keep pushing forward!",
    "You are capable of amazing things!",
    "Every day is a new opportunity!",
    "Believe in yourself and your dreams!",
    "Success is just around the corner!",
    "Stay positive and work hard!",
    "Never stop learning and growing!",
    "Your potential is limitless!",
    "Great things take time. Be patient.",
    "Hard work always pays off!",
    "You are stronger than you think!",
    "Trust the process.",
    "Opportunities don't happen. You create them.",
    "Small steps lead to big changes.",
    "Keep learning and improving!",
    "Your efforts will be rewarded.",
    "Believe in your abilities!",
    "Stay focused and never give up!",
    "The best is yet to come!",
    "Challenges make you stronger!",
    "Dream big, work hard!",
    "Your journey is unique. Embrace it!",
    "Stay consistent and see results!",
    "Push yourself beyond limits!",
    "Success starts with a single step.",
    "Learn from failures and move ahead!",
    "Keep a positive mindset always!",
    "Doubt kills more dreams than failure ever will.",
    "You are your only limit!",
    "Be fearless in the pursuit of your goals.",
    "You have everything you need within you!",
    "Make today amazing!",
    "Your potential is endless!",
    "Be the best version of yourself.",
    "Every challenge is an opportunity to grow.",
    "Trust yourself and take action!",
    "Consistency is key to success.",
    "Keep moving forward, no matter what!",
    "Turn your dreams into reality!",
    "Don't stop until you're proud!",
    "Work in silence, let success make the noise.",
    "Stay humble, stay hungry!",
    "Great things happen to those who hustle!",
    "Do something today that your future self will thank you for!",
    "Difficult roads lead to beautiful destinations.",
    "Don't be afraid to fail. Be afraid not to try!",
    "You have the power to change your life.",
    "Never stop chasing your dreams!",
    "A little progress each day adds up to big results.",
    "Surround yourself with positivity!",
    "Learn to rest, not to quit!",
    "Your growth is a journey, not a destination.",
    "Every expert was once a beginner.",
    "The only way to achieve the impossible is to believe it is possible.",
    "Winners never quit, and quitters never win.",
    "No pressure, no diamonds!",
    "Make progress, not excuses.",
    "Stay motivated and focused!",
    "Go confidently in the direction of your dreams!",
    "Take risks and grow!",
    "Your attitude determines your direction!",
    "Be proud of how far you've come!",
    "You are in charge of your future!",
    "One step at a time, one day at a time.",
    "Your mindset shapes your reality.",
    "You are capable of achieving great things!",
    "Success comes from discipline and perseverance.",
    "Your dreams are worth the effort!",
    "Small actions lead to big achievements!",
    "Make yourself proud every day!",
    "Turn obstacles into opportunities!",
    "Fear is temporary, regret is forever.",
    "Don't just dream, take action!",
    "Keep your goals in sight and stay focused!",
    "Strive for progress, not perfection!",
    "Stay true to your vision!",
    "Your future is created by what you do today.",
    "Push yourself because no one else will do it for you.",
    "The harder you work, the luckier you get!",
    "The best way to predict the future is to create it.",
    "Effort + Consistency = Success!",
    "Don't wait for opportunity. Create it!",
    "Your energy is your greatest asset!",
    "Focus on the solution, not the problem.",
    "Make the most out of every opportunity.",
    "Rise up and attack the day with enthusiasm!",
    "Each failure brings you closer to success.",
    "Take action. Don't just wait for things to happen!",
    "Stay patient and trust your journey!",
    "Your hard work will pay off!",
    "Learn something new every day!",
    "You are unstoppable!",
    "Take the risk or lose the chance!",
    "The only way to do great work is to love what you do.",
    "There is no shortcut to success!",
    "Stay dedicated to your purpose!",
    "You have the power to create change!",
    "Great things never come from comfort zones.",
    "Your dreams don’t work unless you do!",
    "Keep striving for excellence!",
    "Turn setbacks into comebacks!",
    "Don't fear failure, embrace it as a lesson.",
    "Success is a journey, not a destination.",
    "You got this! Keep going!",
  ];

  const randomIndex = Math.floor(Math.random() * messages.length);
  return messages[randomIndex];
}

// console.log(getRandomMessage());
